version: '3'

services:
  # gateway
  nest_api:
    container_name: nestjs_gateway
    image: nest-api:1.0.0
    build:
      context: ./gateway
      dockerfile: .docker/Dockerfile
    command: npm run start:prod
    env_file: ./gateway/.env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped