version: '3'

services:
  db:
    image: mariadb
    container_name: db
    restart: always
    hostname: db_host
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: jshop
      MARIADB_USER: jshop_user
      MARIADB_PASSWORD: jshop_test_password
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_USER: jshop_user
      PMA_PASSWORD: jshop_test_password
      PMA_HOST: db_host
      PMA_PORT: 3306
    networks:
      - default

  api:
    container_name: api
    restart: always
    hostname: api_host
    build:
      context: api
      dockerfile: api.Dockerfile
    environment:
      JWT_SECRET: "123"
      JWT_EXPIRESIN: "3600s"
      DATABASE_USERNAME: "jshop_user"
      DATABASE_PASSWORD: "jshop_test_password"
      DATABASE_DATABASE: "jshop"
      DATABASE_HOST: db_host
    ports:
      - "3000:3000"
    networks:
      - default

  frontend:
    container_name: frontend
    restart: always
    hostname: frontend_host
    build:
      context: frontend
      dockerfile: frontend.Dockerfile
    environment:
      VUE_APP_GATEMAY_ADDRESS: "api_host:3000"
    ports:
      - "80:80"
    networks:
      - default

networks:
  default:
    external:
      name: microservices_network
