export const CONFIG_SERVICE_TOKEN = "ConfigService"
export const FILES_SERVICE_TOKEN = "FilesService"
export const PRODUCTS_KAFKA_CLIENT_TOKEN = "ProductsKafkaClient"
export const AUTH_KAFKA_CLIENT_TOKEN = "AuthKafkaClient"
export const CARD_KAFKA_CLIENT_TOKEN = "CardKafkaClient"
export const CART_KAFKA_CLIENT_TOKEN = "CartKafkaClient"