export const CONFIG_SERVICE_TOKEN = "ConfigService"
export const RESULTER_TOKEN = "Resulter"
export const FILTER_TOKEN = "Filter"
export const PAGINATOR_TOKEN = "Paginator"
export const LOGGER_TOKEN = "Logger"
export const PRODUCTS_SERVICE_TOKEN = "ProductsService"
export const CATEGORIES_SERVICE_TOKEN = "CategoriesService"
export const SUBCATEGORIES_SERVICE_TOKEN = "SubcategoriesService"